### ISSUE TITLE
Add Unit tests to the package mil.nga.giat.geowave.core.cli.prefix

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#1005]
There already are a few tests for classes in this package.  Look at the existing tests to understand them.  This is where a lot of the hard work in decomposing JCommander annotations into commandline tools is done, and ultimately will be reused for REST endpoints as well.  Additional tests should be added for JavassistUtilsTest and PrefixedJCommanderTest.

**Comment by mawhitby** [comment]
Tests added in PR #1022
