### ISSUE TITLE
Improve test coverage within geowave-core-cli

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#1006]
Most of the packages do not have unit tests.  GeoWaveMain, VersionUtils, DefaultPluginOptions, ExplainCommand, HelpCommand, ListCommand, SetCommand, ConfigOptions, and OperationRegistry are classes that would be good to understand and test.

**Comment by Xinmei95** [comment]
When creating the unit test for ExplainCommand, I am thinking of creating an instance of OperationParams. I am wondering what is a good way to set values for its fields? I am trying to follow the way GeoWaveMain did, but it seems that I will have to make an OperationParser and call function parse. Is this a good approach to do it? My concern for this approach is mixing different modules together when doing the tests.

**Comment by mawhitby** [comment]
Using an OperationParams instance seems like a good (and possibly necessary) way to go about testing the ExplainCommand class. As long as you aren't specifically testing the methods in the OperationParams class I don't see it as an issue. Many classes in the project would be impossible to test using only the other classes in their specific package.

**Comment by rfecher** [comment]
pulled in via https://github.com/ngageoint/geowave/commit/f7d190c6367101dee2db5a34c7bbf00fc051194d
