### ISSUE TITLE
Remote submission of existing mapreduce jobs on yarn

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#128]
For the ingest framework and the analytics, we currently allow submission to the job tracker which no longer exists for yarn (replaced with a resource manager).  We want to continue to enable remote submission to the yarn resource manager.  Investigate adding yarn.resourcemanager.address and mapreduce.framework.name within the job configuration.

**Comment by chrisbennight** [comment]
requirement shelved for remote admission of yarn/mr jobs
