### ISSUE TITLE
Create Mapnik data source

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#13]
Develop a mapnik geowave  datasource plugin:
* This will enable mapnik to render tiles directly from a geowave datastore. [1][2]
* Mapnik is behind most of the OSM infrastructure - enabling this brings in lots of great features
* Initial target would be 3.x unless something comes up[3]

Decision point on RPC (thrift, etc.) vs. in-process (Jace[4] probably)
See #14 - same technique here applies there

ref: 
[1]  https://github.com/mapnik/mapnik/wiki/PluginArchitecture
[2]  https://github.com/mapnik/mapnik/wiki/DevelopingPlugins
[3]  https://github.com/mapnik/mapnik/issues?milestone=15&state=open
[4]  https://code.google.com/p/jace/wiki/Overview

**Comment by jwomeara** [comment]
As the pull request is out there and we're just maintaining it until it is accepted, I'm going to close this ticket.  We've also added geowave to mapbox's custom mason dependency manager, so I think we're good.
