### ISSUE TITLE
Create pointcloud (LAS probably) ingester

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#15]
Load pointcloud  (3d / 3d + temporal) into geowave.  

Investigation on access efficiency
 * Load each point as an individual point (vector)
 * Store a volumetric space and index it by the volume  (tiling in 3 dimensions)

Access mechanism:  look to #14 as one of the potential use cases

**Comment by chrisbennight** [comment]
@jwomeara - stick a fork in it?

**Comment by jwomeara** [comment]
As long as we're ok offloading this responsibility to PDAL, yeah.

**Comment by chrisbennight** [comment]
Supported through PDAL (though not part of the ingest framework)
