### ISSUE TITLE
Implement OSM ingest plugin

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#158]

**Comment by chrisbennight** [comment]
I'm leaning away from making this a plugin, and instead a separate package.  If we only supported a one time ingest then we could probably work within the ingest framework, but we want to support delta updates, and for that we need to maintain a persistent ways/nodes/relations table.  

This means ingest looks like

files -> mapreduce -> ways/nodes/relations -> mapreduce -> simple features

And for the case of delta updates we ideally don't want to do a full ways/nodes/relations -> mapreduce -> simple features step, but rather only process changed items.

There's also the case of simple feature representations are typically a subset, or view on the ways/node/relations data, and there may be use cases where we want to make multiple different views - so it's a bit different than the standard ingest workflow.

**Comment by drew-bower** [comment]
Let's discuss.

**Comment by chrisbennight** [comment]
Re: discussion earlier - here's my initial cut at a proposal for the feature:
https://github.com/ngageoint/geowave/wiki/Support-Full-OSM-Stack-Toolchain

**Comment by chrisbennight** [comment]
Due to dependencies and other requirements it makes more sense to build this as a separate project with a dependency on geowave.   Refactoring existing code and will move to here:
https://github.com/ngageoint/geowave-osm
