### ISSUE TITLE
Create a wrapper script for geowave-ingest

### ISSUE THREAD

**Issue by spohnan** [ngageoint/geowave#161]
* A wrapper script named geowave-ingest will be linked into the standard user path and remove the need to preface the command with java -jar XXX.jar
* A bash code completion function will be registered that will help users discover the (sub)options available using the standard "double tab" bash command complete functionality 
* Both of these files will be added to the existing packaging so it all gets put into place and managed via the existing geowave rpms

**Comment by rfecher** [comment]
looks to be completed in merge request #162
