### ISSUE TITLE
Provide consistent way to uniquely identify raster tiles for GeoWaveInputFormat

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#163]
Currently data ID is meaningless for raster tiles but for GeoWaveInputFormat there needs to be a way of uniquely identifying each tile.
Passing index+insertion ID as data ID for GeoWaveInputFormat would make sense, but for raster data this is a special case that needs to be implemented.

**Comment by chrisbennight** [comment]
@rfecher 
might be done - verify

**Comment by rfecher** [comment]
This should basically OBE - the idea is that with tiled data that is clipped along SFC boundaries (ie. raster tiles, but also vector tiles) that the data is different for different SFCs (ie. different indices) so index+insertion ID would uniquely identify a tile.

However, since the creation of the ticket, we are only querying a single index per adapter through our GeoWaveInputFormat, so unique identifiers across multiple indices doesn't seem to be as necessary as it was, and the current GeoWaveInputKey is unique for adapters (ie. adapter ID + insertion ID is unique for a single index, but not unique across indices, but you can no longer query the same adapter across multiple indices)
