### ISSUE TITLE
Integration tests do not properly update zookeeper port for geoserver plugin

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#179]
The datastore config is located in:
https://github.com/ngageoint/geowave/blob/master/geowave-test/src/test/resources/mil/nga/giat/geowave/test/gs.zip

And has the value {{ZOOINSTANCE}} for the zookeeper port, which gets replaced by the randomly generated port.

The directory gs.zip is unzipped here:
https://github.com/ngageoint/geowave/blob/40b6cbbce4dc304539835b264e658cad4d2f16a7/geowave-test/src/test/java/mil/nga/giat/geowave/test/GeoServerIT.java#L65

There is a test that is supposto check if the sizes are different, but it does not appear to work properly - on both a win 8.1 system and Ubuntu 14.04 LTS box the file doesn't get over-written.   

When a new instance is run, the logic fails to find the term {{ZOOINSTANCE}} to replace (just the localhost:83473 (or whatever port number)).

This results in an old datastore.xml file with an incorrect ZooKeeper port, and thus lots of errors in the logs and failed integration tests.

This issue might be fixed by the upcoming integration test changes (get that binary out of there!) - but will leave the ticket open until then to verify it's fixed.   Otherwise the extracted files could simple be deleted in the teardown method.

**Comment by jwomeara** [comment]
Fixed as of  #188
