### ISSUE TITLE
Temporal CQL filter always attempt to use SPATIAL_TEMPORAL index even if it doesn't exist

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#189]

**Comment by rwgdrummer** [comment]
There is a disparity between the numeric data extraction for indexing, the index selection and the query filter selection.  The assembly of the spatial temporal query is currently agnostic to the configuration of the adapter and the index.

**Comment by rwgdrummer** [comment]
I believe this issue is closed.
