### ISSUE TITLE
Integration test not loading decimation process

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#204]
```
27 Jan 23:28:01 ERROR [geoserver.rest] - 
org.geoserver.rest.RestletException: java.lang.RuntimeException: Unable to find function Decimation
```
per @rfecher looks like a namespace issue (should be nga:Decimation) - probably error in style

**Comment by jwomeara** [comment]
Haven't seen this one in a while; either on Travis or Jenkins.  Time to close?
