### ISSUE TITLE
Store statistics for time ranges & connect up to datastore

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#218]
When temporal ranges are enabled in geoserver right now a full table scan is initiated to determine the minimum and maximum bounds.  We need to create a statistics implementation for quantifying the time range, and wire it up to the datastore so the statistics are used (same thing we do for bounding extents).    Might need a little investigation on how multiple time dimensions are handled  (and we should probably store stats for all time types)

**Comment by rwgdrummer** [comment]
current investigation: Need to check with Carrie about version.  I believe a recent fix concerning temporal constraints may solve this issue.    That being said:
(1) Confirmed that we absolutely need time constraints for temporal indices to manage binning, irrespective of GeoServer adapters.
(2) Found a bug with respect to ranges in composing the query filter that creates a range of 0. That fix will go into this ticket.

**Comment by rwgdrummer** [comment]
Ref to 'same thing we do for bounding extents'.  I do not believe that code bounding extents is sufficient.  Bounding boxes is handled loosely in the adapters to provide envelopes.  We do not enforce there use when validating/constraining queries.  If a spatial constraint is issued for a index that supports temporal, than all bins for all time computed.  If a time temporal constraint is computed, the performance is better from a bin standpoint, but still ends up creating a series of ranges on each tier for space (not that bad if its all space, right?).

In all blocks of the code, we use the following to get the numeric constraints:
final MultiDimensionalNumericData indexConstraints = query.getIndexConstraints(indexStrategy);

I am thinking that we should change statistics to associate with the dimension definition IDs (lat, long, time) so we have an understanding on how ranges can be clipped.  For example, a query for a larger domain can be clipped down to the range of specific data set.    Where do we insert this clipping?  One place is BasicQuery.  BasicQuery construction takes the constraints and makes them available per dimension as provided by the index.  
Problems with the BasicQuery approach are : (1) BasicQuery reflects he query, not the index.  So a Spatial Query on a Temporal index is still going to produce binning over the entire of time (0 to Long.MAX_LONG).    This can be solved by have basic query consult the statistics for those dimensions provided by the index model, regardless of what is present int the query.  (2) BasicQuery is limited in its reach, only used in adapters. Despite these set backs, the changes to handle BasicQuery are far smaller that the alternative that I see.

An alternative is to push the stats down the index strategy as an extra argument to the two 'getQueryRanges' methods.  The statistics are based down as a 'MultiDimensionalNumericData statsRanges'.  Problem here is that the data store and its components are several layers above.  Looking at AccumuloConstraintsQuery, the code that instantiates this class (or subclasses) general has access to the store, permitting the introduction of the new constraints.  This affects more code and begins to get ugly.

**Comment by rfecher** [comment]
Hmm, we'll have to talk this one through I suppose...I think when Chris said "same thing we do for bounding box" I don't think he meant literally the same class or anything, right?  Can't we just have TemporalStatistics or something to that effect?  For that matter we can keep ranges as a statistic for any numeric attribute so I would think we would just treat extend from something like a NumericRangeFieldStatistic for a TemporalStatistic that handles time so that we may have some room to grow that concept out.

**Comment by rwgdrummer** [comment]
The key interception point for dealing with clipped default values is the Constraints class within Query.  The method getIndexConstraints gets interrogated, and uses the dimensions full range of values if a provided constraint does not exist.
				
				I see several options at this point.
				option 1: wrapper around numeric index strategy to lookup better set of defaults:  but this may come from the index persisted in the store and the index does not determine the statistics, the adapter does.
				option 2: Provide numeric data along with a default indicator.  
				
				Keeping the index separate from the statistics maintains separation of concerns. Stats is be managed on fields that are not indexed.  
				However, we should consider maintaining stats on ALL indexable fields.  In doing so, indexes can be assured that stats exist for an field.
				Each Index can provide a statistic for efficacy towards a particular query, creating a method of comparison between indices.
				
				What about just adding a query planner as a first class citizen?   
				It takes the adapter, the set of indices and a query, provides the optimal use of indices.  For example, consider a bounding box query with an additional constraint on a discrete attribute. 
				In simple cases, in index on the discrete attribute is preferred over the spatial index.  More intelligent analysis may choose the constraint with a lower number of rows searched.  Determining actual rows searched within a bounding box may be challenging.
				However, histograms over some predetermined bounding boxes  might be sufficient.

**Comment by rfecher** [comment]
ahh, I get it, we're looking to enable an unbounded query for a given dimension.  I read the ticket as supporting a bounds look up on time, essentially assuming when you configured a time field in the geoserver admin UI it would want to compute the time bounds. If we're talking about supporting an unbounded query, if we choose to support it, shouldn't we just treat it as a full table scan?  In general, when we hit an index, we'd hope that the query dimensions are fully qualified, right?
