### ISSUE TITLE
Add ability to add, remove, and re-compute statistics separate from ingest

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#239]
Right now statistics are only computed on ingest.  Consider the use case of building a new statistic, and deploying that.  We should be able to run a MapReduce or some other distributed job to perform a scan over the entire data set and compute selected statistics.   The method should be able to take multiple staticstics instances and compute them all simultaneously in one pass.
Existing statistics should also support a re-compute and remove operation as well.

**Comment by rwgdrummer** [comment]
Options include:
(1) Delete and recompute select statistics.  The use case being that something change invalidating current statistics.  It could be a data store image concern, algorithm concern, etc.
(2) Recompute new statistics.  

In all cases, statistics computations 'can' be selective.  Data Adapters provide a list of statistics.  By default, all statistics are computed.  A wrapper should intercept the request for statistic IDs from the adapter, filtering out those statistics not present in the selected set.

When recomputing existing statistics, the prior image of the statistics must be removed from the statistics store.  

Select query methods have already been altered to support a 'scan' callback. One such callback allows creation of a set of statistic instances.   

A  geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/util/StatsTool.java exists (branch GEOWAVE-218, pending merge to master) provides the basis for the improvement.  The tool deletes all statistics for a given adapter and recomputes the statistics.   The issues with the tool are evident:
- The tool does not work in Map/Reduce.
- Forcing the re-computation of all statistics for an is adapter unnecessarily costly for the most likely scenario--adding a new statistic.
That being said, the tool demonstrates the use of StatsCompositionTool as a callback function for recomputation.

Branch GEOWAVE-218. also contains the Scanner Callback, critical to the support of the effort.
Until branch #GEOWAVE-218. is merged, any work on this task should branch off of #249 .

**Comment by rwgdrummer** [comment]
Notes on Map/Reduce. 

The GeoWaveInputFormat does not pass on the complete set of row entry information including the visibility.  The scan callback and statistics infrastructure requires the complete set of row entry data.  This is one reason why the scan callback approach was used--allowing information to be gathered in the row decoding process.

**Comment by chrisbennight** [comment]
@rwgdrummer this is done, right?
