### ISSUE TITLE
Documentation generation / travis speed issue

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#257]
The new site/documentation code runs after_success, which prevents it from ever being cached, so the maven dependencies are re downloaded each run.

Suggestion:
  Move doc statement to the install phase
  Add a conditional to check the branch and only run on master ( should be exposed as $TRAVIS_BRANCH)

**Comment by spohnan** [comment]
As the documenation generation portion of the build is both a somewhat CPU intensive task and uses a non standard toolkit I don't know how much we can really speed up the operation.

The entire toolchain that transforms from AsciiDoc to the various other products is Ruby based with what amounts to a shim using JRuby and a Maven plugin to work in a Java environment. JRuby is loaded as a standard Maven dependency but all the gems are downloaded to target/gems and are not stored in $HOME/.m2 but as it's a configurable setting I suppose we could tweak the config a bit to make it cachable.

Before we go down that road, however, I'd ask if the Travis build is the right place to be testing every build combination and longer duration operations like javadoc/doc/site generation. Travis has great integration with lots of online utilities like GitHub, Coveralls etc. and is perfect for whatever tests we need to run to determine if something should be merged but at some point could we offload the exhaustive testing and other updates like docs and site generation to Jenkins?

In the project settings there is a Deploy keys area where we could add the Jenkins public key to enable it to push docs. I'd want to figure out a better notification solution for Jenkins (we need an SMTP server) so any build failures could trigger an email to the GeoWave Developers list before we migrated any of the build configurations to Jenkins exclusively.

Looking at the .travis.yml file we could probably halve the number of builds in the travis build matrix and remove the javadoc/doc/site generation tasks. Depending on how many build worker nodes we want to provision for Jenkins we could support all these builds and test against jdk1.8, it's just a matter of how timely you want the complete suite to be run that would determine the number of build worker nodes required.

**Comment by chrisbennight** [comment]
Couple of points
  * I think reducing the number of builds to 4 would be good;  cloudera-current, hortonworks-current, apache-current, and maybe and probably a n-1 of accumulo or geoserver.  I think this is a good middle ground to the "exhaustive testing" location you brought up (we want enought there so the travis tests are meaningful).
  * Moving the exact code to the before install should get us caching of all the maven artifacts;  I think that's an easy win.
  * Didn't look at the documentation scripts / ant tasks, but if we can only run them based on an enviornmental variable that would give another big speed boost.
  * I agree on the Ruby, JRuby stuff, etc.  - don't think that's worth the tradeoff chasing down - I was just looking for little tweaks.

**Comment by chrisbennight** [comment]
Check out #260 - that's basically all I was talking about (well, the POM reformatting was extraneous)
I did reduce the number of runs per suggestion

**Comment by spohnan** [comment]
Looks good
