### ISSUE TITLE
GeowaveServicesIT seems to depend on GPX data extracted in another test

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#258]
Tests should be self-contained and not dependent on another test case.

**Comment by rwgdrummer** [comment]
Rich...did you fix this in the lastest Raster merge...thought I noticed a fix.

**Comment by chrisbennight** [comment]
@rfecher confirm/deny Eric's question!

**Comment by rfecher** [comment]
Thanks for bringing this to my attention @chrisbennight!

I did not, #103 was addressed, but @jwomeara promised he's re-address this when we triaged issues last week.

**Comment by chrisbennight** [comment]
Let's find out!
https://github.com/ngageoint/geowave/commit/30f855ccdcdfc601d85d1a939ef0279bbe488d45
https://travis-ci.org/ngageoint/geowave/builds/55466793

**Comment by jwomeara** [comment]
Super green!
