### ISSUE TITLE
RPM build jobs failing

### ISSUE THREAD

**Issue by spohnan** [ngageoint/geowave#261]
The RPM jobs are failing due to a bad refactoring of the various documentation transformations I pushed in the last documentation and site update commit.

In an attempt to keep the documentation source DRY I wanted to include the manpage content in all the other products so there would only be one source file to update. Unfortunately, the manpage source has to be in exactly the format it expects (spacing and section naming conventions) or it will fail while the other formats (HTML, PDF and EPUB) are much more forgiving. 

The proposed solution will be to run a sed preprocessing operation on source before running the man page transformation so it can get the exact format it expects which can be escaped from evaluation in the other formats.

**Comment by chrisbennight** [comment]
Does #262 fix this?

**Comment by spohnan** [comment]
Fixed with #262
