### ISSUE TITLE
Reduce size of the images in the Documentation page as it takes lot of time to load

### ISSUE THREAD

**Issue by viggyprabhu** [ngageoint/geowave#274]
Currently [Documentation Page](https://ngageoint.github.io/geowave/documentation.html) takes forever to load as it has lot of images which in all around 7MB together. We can try to decrease the size of the images, using sites like Tinypng.com or some other best known methods.

**Comment by spohnan** [comment]
An oversight on my part that also affects the main website page. I'll get them reduced to a more reasonable size. Thanks for pointing out the problem.

**Comment by chrisbennight** [comment]
probably good to do this in concern with #252 if it's still valid.

**Comment by chrisbennight** [comment]
#293 Hits most of this
