### ISSUE TITLE
Geospatial benchmark utility

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#28]
Develop a spatial (and consider temporal) benchmark utility that can be generally applicable to run against any system that stores, indexes, and retrieves spatial content.  Likely this will be most generally done by keeping it separate from GeoWave, and utilizing GeoTool's data store abstraction.

**Comment by chrisbennight** [comment]
We have a benchmark for the point cloud capabilities in geowave-benchmark;
A geotools/feature specific benchmark is currently in the works with CCRi.
