### ISSUE TITLE
Exception when exposing data through geoserver with more than two date fields

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#283]
Exception (no stack trace handy) reported in this case

**Comment by chrisbennight** [comment]
Might want to implement something similar to what elasticgeo has done for configuration of display feature type (this is assuming that's part of the issue here):

https://github.com/ngageoint/elasticgeo/blob/master/gs-web-elasticsearch/doc/index.rst#configuring-an-elasticsearch-layer

**Comment by rwgdrummer** [comment]
Agreed.  Cannot find the ticket for this enhancement, but it is the same panel described here: #72
In the mean time time.  I should fix this.

**Comment by rwgdrummer** [comment]
closing issue since bug is fixed.  However, the comment made by Chris is linked to #72.   This, ultimately, is the correct fix.  I am going to another ticket to add parameters to the ingest process as well.
