### ISSUE TITLE
Allow ingest of simple features to configure the feature type labeling time attributes for temporal indexing

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#288]
Per #283,

The ingest process for simple features should accept a list of time attribute names to be used for temporal indexing, overriding the inference component of the FeatureDataAdapter.
One time attribute indicates an index over a single attribute.  Two attributes represent a range (start and end).

In the case of a single time attribute, the simple feature type meta-data property 'time' is to a Boolean value TRUE.
In the case of a range time attributes, the simple feature type meta-data property 'start' is to a Boolean value TRUE for the start range attribute and  the simple feature type meta-data property 'end' is to a Boolean value TRUE for the end range attribute.

The setting of these meta-data properties is performed prior to construction of the FeatureDataAdapter.

If any these attributes are set,  then a spatial temporal index should be assumed during the ingest process.

**Comment by rfecher** [comment]
I've been looking at #146 and started some work on it which seems related (ie. not all ingest plugins want to advertise setting a time attribute).  Additionally I think that ingest plugins based on SimpleFeature data should be able to provide a CQL filter string set on the commandline to allow a user to specify only ingesting a selected subset of a larger dataset (I just created #289 for this).

**Comment by rwgdrummer** [comment]
Completed with branch for #421
