### ISSUE TITLE
Package download updates

### ISSUE THREAD

**Issue by spohnan** [ngageoint/geowave#338]
RPM package downloads and documentation updates:

* The [original package download page](http://s3.amazonaws.com/geowave-rpms/index.html) should be replaced with a forward to the [new download page](http://ngageoint.github.io/geowave/packages.html) which is now hosted on github.io instead of manually copied into S3 and is also [version controlled](https://github.com/ngageoint/geowave/blob/master/docs/content/packages.html)
* The [new download page](http://ngageoint.github.io/geowave/packages.html) only lists available packages correctly from http. Would like it to work from http(s) but can just redirect back to http if needed
* Suggested improvements to RPM install documentation

**Comment by chrisbennight** [comment]
#339
