### ISSUE TITLE
Integrated support for public LandSat8 data on AWS

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#346]
The [LandSat 8 data](http://aws.amazon.com/public-data-sets/landsat/) is organized as GeoTiffs in S3.

This capability will provide a new custom ingest operation for landsat ingest that will take in the accumulo connection parameters, a working directory (that the [geometry for the scenes] ([geometry for scenes] (http://landsat.usgs.gov/documents/wrs2_asc_desc.zip) can be downloaded into) and expect to have access to the S3 data and supplemental data.  It will bring the supplemental data into the working directory and access the landsat data within S3 to ingest the appropriate geotiffs. 

The user can give a CQL expression to filter which geotiffs are ingested.  The feature type that the filter is applied to will have the following fields:
entityId,acquisitionDate,cloudCover,processingLevel,path,row,min_lat,min_lon,max_lat,max_lon,download_url, AREA,PERIMETER,PR_, PR_ID,RINGS_OK,RINGS_NOK,WRSPR,PR,MODE,DAYCLASS,SEQUENCE,geom

**Comment by datasedai** [comment]
90% code implemented in Geowave-346 branch.
