### ISSUE TITLE
can't find mil.nga.giat:geowave-dev-resources?

### ISSUE THREAD

**Issue by jfritschsonatype** [ngageoint/geowave#362]
Hello,

I am trying to build GEOWAVE from source and can't find mil.nga.giat:geowave-dev-resources in either a public repository or the S3 Release and Snapshot repo's at http://s3.amazonaws.com/geowave-maven/release/ or http://s3.amazonaws.com/geowave-maven/snapshot/ .

Can someone point me to where the geowave-dev-resources are stored?

Thanks

joe
jfritsch@sonatype.com

Here is the error I am receiving:

[ERROR] Failed to execute goal com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4:format (default) on project geowave-parent: Execution default of goal com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4:format failed: Plugin com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4 or one of its dependencies could not be resolved: Could not find artifact mil.nga.giat:geowave-dev-resources:jar:1.0 in nexus ...

**Comment by dcy2003** [comment]
Hi @jfritschsonatype -

You will find a dev-resources folder at the top-level of the project repository.  First, run `mvn install` from within the dev-resources folder to build and install that project to your local .m2 repository, and then rebuild from the root directory and you should be good to go.

**Comment by chrisbennight** [comment]
@jfritschsonatype - 

Yep, for now you probably have to do a local install;  we just merged in a large refactor probably 30 minutes before you pulled ( #320 ) and our jenkins just hasn't built artifact yet;  

There should be a new nightly up later on tonight (in snapshots) - not sure off the top of my head what time jenkins is set to build nightlies.   Alternatively if you check out  the 0.8.6 tag - 
 https://github.com/ngageoint/geowave/tree/v0.8.6  - that should have full dependencies in maven.  If you are trying to deploy I would recommend giving us a day or two to get any changes that need to be sorted out after the re-factor sorted out (there are a few packaging, etc. issues).

But if you want to build master, then @dcy2003 comment is the way to go - a mvn install will install that artifact locally.

hope that helps, and sorry for any confusion - you just caught us in the midst of a large re-factor.

**Comment by chrisbennight** [comment]
@jfritschsonatype 
just published to maven in our release repo, and should have a pull request shortly that adds that repo into the repositories section.

**Comment by jfritschsonatype** [comment]
Thanks Chris and Derek,

 

The build continued past the error from yesterday as the geowave-dev-resources is now in the release repo.

 

Thanks again.

 

Joe

 

 <http://www.sonatype.com/> 

 

Joe Fritsch <http://www.linkedin.com/in/joefritsch/> 

Director of Technology, Federal

Office: (301) 684-8080 x-145

Mobile: (703) 626-0508

 

Sonatype Nexus Professional <http://www.sonatype.com/take-a-tour/nexus-pro-tour> 

Sonatype Component Lifecycle Management (CLM) <http://www.sonatype.com/take-a-tour/clm-tour>
