### ISSUE TITLE
Build fails when resolving dependencies for geowave-deploy

### ISSUE THREAD

**Issue by ScottEvil** [ngageoint/geowave#364]
I'm trying to build GeoWave on on Ubuntu 14.04 with Maven 3.0.5. Accumulo is set up. When I try to use maven to build, it successfully downloads all artifacts until it gets to: geowave-vector, geowave-raster, and geowave-utils. 

For geowave-utils it complains that it can't find the jar at http://repo.boundlessgeo.com/main. I checked the url and there isn't a folder called mil/nga/giat (or any that contain the jar in question). 

Ideas on how to work around this? Cheers!

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.970s
[INFO] Finished at: Sat May 02 17:54:16 EDT 2015
[INFO] Final Memory: 8M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project geowave-deploy: Could not resolve dependencies for project mil.nga.giat:geowave-deploy:jar:0.8.7-SNAPSHOT: The following artifacts could not be resolved: mil.nga.giat:geowave-vector:jar:0.8.7-SNAPSHOT, mil.nga.giat:geowave-raster:jar:0.8.7-SNAPSHOT, mil.nga.giat:geowave-utils:jar:0.8.7-SNAPSHOT: Could not find artifact mil.nga.giat:geowave-vector:jar:0.8.7-SNAPSHOT in boundlessgeo (http://repo.boundlessgeo.com/main) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by chrisbennight** [comment]
Did you run a mvn install first?   (don't have snapshots published yet, nightlies haven't run for 0.8.7-SNAPSHOT)

I just ran this on an ubuntu 14.04 box with maven 3.1.1 (but don't think that should be an issue)

```
cd geowave;
cd dev-resources;
mvn clean install;
cd ..;
mvn clean install;
```


(Did catch the dev-resources packaging issue - I'll make a separate ticket for that; it just needs to be published to maven and our repo added)

**Comment by rfecher** [comment]
we could publish dev-resources to maven central

**Comment by rfecher** [comment]
it looks like the artifacts it is looking for is pre- #320 (major refactor)
are you trying to build from "geowave-deploy" after you updated with the latest commit?
If so, it must be a stale pom.xml in geowave-deploy still around, because it is now "deploy" instead.

**Comment by ScottEvil** [comment]
Yes, I was in geowave-deploy. I'll rerun with the mvn clean install after cloning fresh and then I'll try to build again. 
BTW, is there a mailing list for these sort of questions where I'm not sure if it's my error or an actual issue? Or are you using Gitter for that?

Thanks for the help!

**Comment by chrisbennight** [comment]
@rfecher just published  geowave-dev-resources earlier, and pull request inc #366 :) https://s3.amazonaws.com/geowave-maven/release/mil/nga/giat/geowave-dev-resources/1.0/geowave-dev-resources-1.0.pom  .  I don't think it's looking for a pre #320 resource - geowave-deploy is still the artifact name - I think it just couldn't resolve those dependencies as it needed a local mvn install on the parent pom first.   On a release it would have resolved from the release repo, but probably a bad idea to add the snapsot repo as a repository, as we want it to build locally (mvn install)

@ScottEvil Re: mailing list;  yeah, we probably should put one together - I think @rfecher did awhile ago, but we never really started using it.  No problem using issues or gitter, but we will get the mailing list thing going and add it to the Readme.md / documentation.

**Comment by rfecher** [comment]
@chrisbennight the dependencies that it was trying to find are the old names (geowave-vector, geowave-raster, geowave-utils, etc.). Thats what hinted me that he must be running from an old "geowave-deploy" directory.

I just merged Chris's change to reference a maven repository on s3 that has the dev-resources so we should be covered on this issue, closing...

(@ScottEvil let me know if this doesn't actually work for you, but I *think* it should)
