### ISSUE TITLE
RPM package refactoring

### ISSUE THREAD

**Issue by spohnan** [ngageoint/geowave#370]
1. Refactor RPM packaging to support concurrent version installs
 * Use alternatives to maintain softlink at /usr/local/geowave to most recent version
1. Refactor RPM packaging for the old geowave-ingest tool
  * New jars will be under /usr/local/geowave/tools
1. Refactor old geowave-ingest helper script to become the new "geowave" helper script which will use the new tools framework
   * geowave tools script will have all jars in /usr/local/geowave/tools/plugins directory on the classpath
1. Create RPM sets for the Apache and Hortonworks vendor profiles
1. Tweaks to the build scripts to reflect recent project layout restructuring
1. Update documentation to reflect the changes to the packaging and new tool that replaced geowave-ingest
 * 041-statistics.adoc
 * 050-framework.adoc
 * 055-ingeststandalone.adoc
 * 060-ingestplugins.adoc
 * 075-install-from-rpm.adoc ("ingest" is probably not in the name of the GeoWaveMain commandline tool rpm anymore?)
 * 080-install-from-source.adoc
 * 085-accumulo-config.adoc ("ingest" is probably not in the name of the GeoWaveMain commandline tool rpm anymore?)
 * 090-building.adoc (bottom section talking about avro)
 * 095-jacejniproxies.adoc ("geowave-deploy" path references need to be replaced with deploy)

**Comment by jwomeara** [comment]
095-jacejniproxies updated with #379

**Comment by spohnan** [comment]
completed with release of v0.8.7
