### ISSUE TITLE
FeatureDataAdapter and FeatureWritable do retain Axis orientation on EPSG:4326

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#385]
A CRS lookup with SRID of 4326 returns lat/long.  When serializing a FeatureDataAdapter or a FeatureWritable, the Axis orientation is not preserved.  IN some cases, when deserialized, lat/long is assummed.  This the Axis orientation must be preserved.  This also respects that input data may in fact be lat/long.

If the input data is long/lat and is serialized into an intermediate file (sequence file, for example) and then read back, the FeatureWritable assumes lat/long.

**Comment by chrisbennight** [comment]
We can default to CRS84 which should solve that (and keep thins in lon/lat)

**Comment by rwgdrummer** [comment]
I tried that and ran into another issue.  The CRS84 does not have a standard SRID.

**Comment by chrisbennight** [comment]
No big deal as long as it's consistent, we just have to make sure it doesn't end up biting us internally.

```
urn:ogc:def:crs:OGC:1.3:CRS84
```

Should be the full definition  

See 
http://wiki.geojson.org/GeoJSON_draft_version_6 
(section 4.3.1) for references, etc.
