### ISSUE TITLE
Develop Hbase extension to Geowave

### ISSUE THREAD

**Issue by viggyprabhu** [ngageoint/geowave#406]
Currently GeoWave supports only Accumulo as the DataStore. Hbase, similar to Accumulo is an open-source, scalable, distributed, versioned, non-relational database modeled after [Google's Bigtable paper](http://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf). It makes use of the distributed data-storage provided by Hadoop and HDFS. Though based on same paper, Accumulo and Hbase have some common features and quite a few differences also. Hence we need to add support for Hbase in GeoWave and the user should be given an option to choose between Accumulo and Hbase depending on his/her use-case. This will ensure that users of GeoWave can make use of the best of both the worlds.

**Comment by viggyprabhu** [comment]
@rfecher suggested me to implement features following in order to start with:
1) Client ingest (just using a connection from the caller of the data store API)
2) Basic mapreduce ingest (using something like GeoWaveOutputFormat)
3) Bulk mapreduce ingest (using HFileOutputFormat to write offline)
4) GeoServer plugin 
5) Mapreduce analytics

**Comment by rwgdrummer** [comment]
Statistics caching is currently part of the solution to avoid repeated look-ups that aggregate statistics.  Consider, statistics get update from different threads/clients (WFS-T).  The statistics cache cannot be assumed to be up to date.  The caching is turned off in the Accumulo implementation (see addObjectToCache in the statistics store class).

**Comment by timrobertson100** [comment]
There aren't any commits linked. Is the closed as "won't fix" please?

**Comment by rfecher** [comment]
No, it looks like the commits didn't reference the issue #, but this one did get wrapped up.  HBase specific code has gone [here](https://github.com/ngageoint/geowave/tree/master/extensions/datastores/hbase).
All of the basics will work with vector data, but there is an issue with raster data in HBase which will be resolved this next release cycle (0.9.3).   You can follow any HBase related issues with [the "hbase" label](https://github.com/ngageoint/geowave/issues?q=is%3Aissue+is%3Aopen+label%3Ahbase).

**Comment by timrobertson100** [comment]
Thanks @rfecher
