### ISSUE TITLE
Accumulo 1.7 support

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#422]
Project should build/test against 1.7

Also, related discussion about dropping 1.5.x support

**Comment by chrisbennight** [comment]
Looks to be mostly tied to our use of tablet locator;  specifically due to how credentials are passed in.
Mostly here:
[GeoWaveInputFormat.java](https://github.com/ngageoint/geowave/blob/master/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/input/GeoWaveInputFormat.java)

One small other small change to the GeoWaveDemoAppShell
[GeoWaveDemoAppShell.java](https://github.com/ngageoint/geowave/blob/master/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/app/GeoWaveDemoAppShell.java)
the location of the accumulo  shell class was moved from

org.apache.accumulo.core.util.shell.Shell;
to
org.apache.accumulo.shell.Shell;

**Comment by chrisbennight** [comment]
We will also want to make sure the command line utils supports pulling kerberos auth from the current session if available (probably via GSSAPI )

**Comment by chrisbennight** [comment]
ref: https://github.com/ngageoint/geowave/compare/accumulo-1.7

  * Drops support for 1.5.x  (don't see an easy way to have a 3 way conditional in munge)
  * We can also completel drop the accumulo_legacy flag and the groovy plugin at runtime
  * Changed munge symbol to look for the variable ACCUMULO_API_VER  where VER = 1.6, 1.7, etc.  This was because many of the packages add extra versions on the end and we can't do a prefix match with munge

ToDo
  * GeoWaveInputFormat needs to be changed in 1.7 to set/pass a ClientContext instead of an Instance member
  * Vagrant projects needs to be updated for new build parameters
  * RPM build process needs to be updated for new build parameters

**Comment by chrisbennight** [comment]
ClientContext changes ripple through here:
https://github.com/ngageoint/geowave/blob/accumulo-1.7/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/input/GeoWaveInputFormat.java#L276

and 

https://github.com/ngageoint/geowave/blob/accumulo-1.7/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/input/GeoWaveInputFormat.java#L309

**Comment by chrisbennight** [comment]
So ran this down a bit more - I think we are going to want to replace all occurences of String password (etc.) for accumulo with an AuthorizationToken instead.

**Comment by chrisbennight** [comment]
Hold on these changes until #238 is closed

**Comment by dcy2003** [comment]
Once we officially drop support for 1.5.x, we should scrap our custom Lexicoders  [here](https://github.com/ngageoint/geowave/tree/master/core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder) and use the Accumulo-provided package [here](https://github.com/apache/accumulo/tree/master/core/src/main/java/org/apache/accumulo/core/client/lexicoder) instead, which was made available in v1.6.

**Comment by meislerj** [comment]
I considered that initially, but I didn't want to introduce an Accumulo dependency to the geowave index project.  Right now, it's not a dependency in the pom.xml for the project.

**Comment by keith-turner** [comment]
I am working on adding Tablet location to the Accumulo API.  I just opened apache/accumulo#53 I am going to try modifying GeoWaveInputFormat to use these new APIs as an experiment.

**Comment by keith-turner** [comment]
I was able to get geowave working with the Accumulo tablet location API changes ( [my branch](https://github.com/keith-turner/geowave/tree/use_locator_api)). Was able to successfully run the geowave test BasicMapReduceIT that @rfecher told me about in the geowave chat room.

**Comment by dcy2003** [comment]
Included in 0.9.0
