### ISSUE TITLE
Add option for more logging from the CLI tool

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#435]
Either '-v' for verbose and toggle more messaging on, or '--debug' which could automatically turn up the log level for log4j (without the user having to hassle with log4j properties)

In general, we need easier ways for users to get more insight into the CLI/ingest processing in cases where it is not matching their expected behavior.

**Comment by datasedai** [comment]
#546 - Add option to programmatically up the log level for log4j.
