### ISSUE TITLE
Move to 2.6.4 / 2.7.1.1 for geoserver

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#438]
Ref:
https://osgeo-org.atlassian.net/browse/GEOS-7032
http://blog.geoserver.org/2015/06/27/geoserver-xee-vulnerability/

Fixed in:
http://sourceforge.net/projects/geoserver/files/GeoServer/2.7.1.1/
http://sourceforge.net/projects/geoserver/files/GeoServer/2.6.4/
http://sourceforge.net/projects/geoserver/files/GeoServer/2.5.5.1/

**Comment by chrisbennight** [comment]
#440 covers this

@spohnan - can you close this after you update our the build_args for our jenkins environment?

**Comment by spohnan** [comment]
We currently vendor the 3rd party binaries from our Jenkins server which will soon be moved to S3 as part of #371 I uploaded the new 2.7.1.1 binary, adjusted the build args for the application and rpm jobs and rebuilt and republished our 0.8.7 release and kicked off a build of 0.8.8-SNAPSHOT.
