### ISSUE TITLE
Store tiers that are actually used in metadata

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#48]
This will allow us to only multiplex SFC query ranges across the tiers that actually have data.

**Comment by chrisbennight** [comment]
related to #193

**Comment by rwgdrummer** [comment]
Only compose ranges for those tiers that have associated data. 
Ideally, use a statistic to capture which tiers are filled .

**Comment by datasedai** [comment]
Please note, there is a branch GEOWAVE-48 that contains the majority of this work.  (Looks to be completed)

**Comment by rwgdrummer** [comment]
merged into master
