### ISSUE TITLE
GeoServer-produced WFS data needs to ensure data field titles are GML-safe

### ISSUE THREAD

**Issue by ewilson-radblue** [ngageoint/geowave#488]
Ingested vector data from a shapefile including column headers with non-GML-safe characters, such as white-spaces.  After creating a vector data store in GeoServer and publishing the layer, trying to preview the layer via GML results in improper XML errors.  This can cause some parsers to fail altogether.

Code should be added to ensure that any produced GML data columns will replace white-space characters with underscores, or some similar protections.

**Comment by dcy2003** [comment]
See issue #690
