### ISSUE TITLE
Handle longitude wrapping on ingest for geolife longitude values (180 -> 400 )

### ISSUE THREAD

**Issue by chrisbennight** [ngageoint/geowave#53]
Geolife dataset (See ingester in current geolife branch, data at http://research.microsoft.com/en-us/projects/geolife/ ) has values longitude values that go up to 400.  Dateline wrapping isn't handled properly for these values.

Should handle on parsing side, as "meaning" of EPSG:4326 values outside the -180/+180 range is undefined, or rather defined by the convention of the data set.

![image](https://cloud.githubusercontent.com/assets/1864782/3668316/ffc0c1ae-1218-11e4-9d66-0815875323d8.png)

**Comment by dcy2003** [comment]
I downloaded both v1.2 and v1.3 of this dataset and did some analysis.  I wrote a little utility to explore the 17,621 trajectories looking for problematic coordinates.  Interestingly enough, there is a **single** coordinate in this entire dataset that causes trouble.  It is [lat=400.167, lng=116.215] and comes from line 6782 of file `20110911000506.plt` (trajectory 20).

I will update the ingest plugin to handle this value accordingly - should be an easy fix.
