### ISSUE TITLE
Improve parsing/handling of command line options

### ISSUE THREAD

**Issue by dcy2003** [ngageoint/geowave#546]
The current approach, using Apache CLI is verbose from a code standpoint and rigid from a usage standpoint (e.g. expects options in a specific order).  Consider replacing Apache CLI with another library such as JCommander or Args4J for improved handling of command line options.

**Comment by chrisbennight** [comment]
JCommander++

**Comment by datasedai** [comment]
Related to #331  - Ensure that CLI errors are shown in a prettier format.
