### ISSUE TITLE
Allow the GeoTools plugin to select a preferred index to 'write' new features for a layer

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#553]
This ticket is a bit of challenge; the only way to capture per layer configuration is through the feature type, which is supported by the adapter.  The preferred index is at it states, a preference.  It does not represent the actual location of the data for an adapter, as an adapter is just a descriptor for a set of data.  It does not state how the data is indexed.

The recommended approach, for simplicity:
(1) Maintain the preferred index name in the feature type meta-data.
(2) When ingesting a new adapter for the first time, set the preferred index to the index to which data is being ingested.  This insures that additional data added through GeoServer is added to the same index.
(3) If the preferred index name does not exist, find the next suitable index available.  If no other suitable index is available, use geospatial.  Historically, temporal indices is not used as a default.

**Comment by rwgdrummer** [comment]
In the merge branch.

**Comment by dcy2003** [comment]
Included in 0.9.0 release
