### ISSUE TITLE
Dead links for Java Advanced Imaging and Java Image I/O in ReadMe

### ISSUE THREAD

**Issue by ScottEvil** [ngageoint/geowave#581]
Under the "Supported versions of core libraries" there are links for the Java Advanced Imaging and Java Image I/O libs that are required by GeoServer for GeoWave. 

However, clicking on those links gives you a page from Oracle that says "We're sorry, the page you requested was not found."

**Comment by binderparty** [comment]
Pull request GEOWAVE-581 updates the links and provide additional information.  Issue closed.
