### ISSUE TITLE
Server-Side (Iterator) Attribute Subsetting for Queries

### ISSUE THREAD

**Issue by dcy2003** [ngageoint/geowave#615]
The recent optimization to flatten attributes with shared visibility into a single CQ broke the original implementation of supporting subsets of attributes server-side (within an iterator) for queries.  This functionality should be re-implemented.  

This ticket depends on #563 

See original ticket #143

**Comment by rfecher** [comment]
take a look at [org.geotools.data.Query](https://github.com/geotools/geotools/blob/master/modules/library/api/src/main/java/org/geotools/data/Query.java#L181) to make sure that when a subset of property names are used within our geotools plugin, that the subset is passed along to geowave QueryOptions to properly subset the attribute
