### ISSUE TITLE
Query can be null and thrown an NPE in the CLI

### ISSUE THREAD

**Issue by esteban** [ngageoint/geowave#637]
I've been trying to find out why the analytics jar is failing now and it seems that it was caused by https://github.com/ngageoint/geowave/commit/349afd78431ca92cebbd446370c99f344d846dce it looks like in PropertyManagement it doesn't check if the value is null and we attempt to convert it:

```
private Serializable convertIfNecessary(
			final ParameterEnum property,
			final Object value )
			throws Exception {

		if (!(value instanceof Serializable)) {
			for (@SuppressWarnings("rawtypes")
			final PropertyConverter converter : converters) {
				if (converter.baseClass().isAssignableFrom(
						property.getHelper().getBaseClass())) {
					return converter.convert(value);
				}
			}
		}

```

Digging further, in PersistenceUtils.toBinary() it neither checks if persistable is null and we throw the NPE in persistable.getClass():

```
public static byte[] toBinary(
			final Persistable persistable ) {
		// preface the payload with the class name and a length of the class
		// name
		final byte[] className = StringUtils.stringToBinary(persistable.getClass().getName());
		final byte[] persistableBinary = persistable.toBinary();
		final int classNameLength = className.length;
		final ByteBuffer buf = ByteBuffer.allocate(4 + classNameLength + persistableBinary.length);
		buf.putInt(classNameLength);
		buf.put(className);
		buf.put(persistableBinary);
		return buf.array();
	}
```
I'm not too familiar with geowave but I'd expect that if there is no -eq value passed in to the CLI it should use a default query. Also I tried to pass a query with no luck.

**Comment by rwgdrummer** [comment]
Stilll wondering why -eq is null.  We know there still outstanding issues in the command line which are being addressed in 0.9.1

**Comment by esteban** [comment]
Thanks for the quick response, yeah the patch should fix the NPE. I haven't digged further why the query is null since I decided just to roll back to 0.8.9, but even if I was getting the NPE.

**Comment by rwgdrummer** [comment]
Understood.  I will take another look next week to see if I can ascertain were to issues are.  0.9.1 requires a re-ingest as we have not finished a migration tool.
