### ISSUE TITLE
All ingest pipelines including WFS-T should insure the creation of meta-data associated adapter to index.

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#652]
The meta-data is used for query processing to decide which indices can be used with which adapters.

To insure ingest and the Geotools are in line with each other, the index selection component of the geotools plugin should be used by import formats that ingest into geotools feature adapters.

**Comment by datasedai** [comment]
It doesn't look like Kafka Ingest has this Adapter Mapping.

**Comment by datasedai** [comment]
I noticed an issue in LocalIngestRunData.  During issue #658, a thread safety issue was introduced.  The temporary 'adapter' cache should not be written to after it is initialized.  There is a comment, right above its initialization that states:

> 		// NOTE: This should be thread-safe because the adapterCache is never
>		// added to after this point. It's a static list.

However, an addAdapter method was created and is being used and called from multiple threads without sychronization.
