### ISSUE TITLE
No assumptions should be made as to what Statistics a Statistical DataAdapter provides

### ISSUE THREAD

**Issue by jwomeara** [ngageoint/geowave#655]
Ran into this when creating a customized FeatureDataAdapter which only persists the bounding box statistic.  

When a query is performed against a namespace which contains valid entries, null is returned because it is assumed that all StatisticalDataAdapters will use RowRangeHistogramStatistics.  The point of failure lies within the DataStoreUtils.trimAdapterIdsByIndex method.  If an adapter doesn't include this statistic, it is assumed that no entries are present in the namespace.

One way to make the logic work would be to persist a list of enabled statistics for each data adapter in the GEOWAVE_METADATA table.  That way, no assumptions need be made about what statistics are included for any given StatisticalDataAdapter.

**Comment by jwomeara** [comment]
After looking at the code a little bit more, it looks like the data store is actually adding this statistic, not the data adapter.  So, instead, there is an assumption that all data stores will add this statistic.  It would still be nice to know if a particular data store provides this statistic before prematurely dropping out of a query.

**Comment by rwgdrummer** [comment]
DataStoreUtils.trimAdapterIdsByIndex  was removed for #658 .  Pull Request pending final review
