### ISSUE TITLE
Store required data statistics for discovering what adapters are in each index

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#660]
`Map<Index,Adapter[]>` basically needs to be around to make decisions on which index to query if multiple indices exist.  This required metadata should be stored and used in place of of RowRangeHistogram which is causing this issue currently: #655

**Comment by rfecher** [comment]
actually the method that would likely be used more often than not is getIndices(ByteArrayId adapterId) or something like a `Map<AdapterId, IndexIds[]>` structure

**Comment by rwgdrummer** [comment]
Should apply this in the delete case as 'check' do not want to have the case where a feature is deleted in one index and not another.
