### ISSUE TITLE
GeoWave Quickstart Guide

### ISSUE THREAD

**Issue by dcy2003** [ngageoint/geowave#688]

**Comment by ScottEvil** [comment]
As a newcomer to GeoWave, I need to be able to quickly stand up an instance of GeoWave, bring in some data, and visualize it. 

The goal of this is to give people a way to set up GeoWave, kick the tires, and understand what it basically does. 

 - Be able to instantiate a small GeoWave instance
 - Ingest some data
 - View in GeoServer

**Comment by mawhitby** [comment]
A quickstart guide was added to the GeoWave documentation in pull request #888.
