### ISSUE TITLE
IndexWriter needs to be closed, flush isn't sufficient unless close is eventually called 

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#696]
This may have to do with Statistics not being written on flush - needs further investigation.  I recommend using BasicKafkaIT to test this.

**Comment by rwgdrummer** [comment]
This is not an issue any longer. Although, we should still add the test to BasicKafkaIT .

**Comment by datasedai** [comment]
I have verified that this is still an issue.  Without .close(), the records are not written.

I also verified that a bug was introduced in #658.  An empty list of indexes is passed to toGeoWaveData, and as a result no data is written to GeoWave.

I am looking into both of these issues.

**Comment by datasedai** [comment]
So, I think the reason this isn't working is that IndexCallbackList<T> is not Flushable.  The callback list is created in AccumuloDataStore.createWriter:
`			final IngestCallbackList<T> callbacksList = new IngestCallbackList<T>(
					callbacks);
`
But, the flush() method in AccumuloIndexWriter only flushes the callback if it is Flushable.  Adding "Flushable" interface to IngestCallbackList seems to have fixed the issue. Pull request soon.
