### ISSUE TITLE
Disable commandline completion

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#697]
Until we provide support for dynamic commandline options (#635) we need to disable any CLI completion support.

**Comment by datasedai** [comment]
As a stopgap, I could write a tool to generate the .sh file based on everything in the current geowave baseline at compile time.  Might be better than nothing?

**Comment by rfecher** [comment]
I'd be ok with it as a stopgap - I'm a little unclear as to when the .sh file would be written though?  would it be part of the rpm install process?  in that case, we could probably just keep the old way of doing things (static file thats checked in with full set of commands)  and it would have the same effect on the user.  The issue that comes into play if we consider the cli truly pluggable is the idea of if the user drops additional libraries in they will not be part of the commandline completion, or if the user removes libraries the commandline completion will still have them.  My only thought is that as part of GeoWaveMain, it could write the file, but I think then it would be kinda weird in that the first time you run it you wouldn't have completion, it would only take effect after running.

Perhaps it comes down to, is commandline completion important to us, and is pluggable components important to us (how static are we willing to consider the components)?
