### ISSUE TITLE
GeoWaveInputFormat: setAdapter and setIndex overrides QueryOptions

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#699]
QueryOptions should be the defacto correct value for indices and adapters.

Perhaps this is a good time to just have the setIndex and addAdapter to pull out the QueryOptions and modify it, rather than having a 'separate' option.

**Comment by datasedai** [comment]
Reviewed

There are two things going on.  It looks like he consolidated a few of the parameters, and then he also added QueryOptions as a parameter and remove Adapter ID and Index ID as parameters. (which compose QueryOptions)

Didn't see any huge issues .. few comments

**Comment by rwgdrummer** [comment]
Yes.  In testing the QueryOptions with the analytics, I noticed some of the parameters were missing from a prior commit, so I fixed them here. 
Now queryoptions fall under a command option class that is a delegated from another command option class.  In the analytics case, the delegate option tag is 'query' (e.g. --query.adapters adapter1,adapter2)
