### ISSUE TITLE
Fix Stanag 4676 service issues

### ISSUE THREAD

**Issue by bmendell** [ngageoint/geowave#758]
As part of the support of Stanag 4676 data, an image server is provided as an extension to GeoWave.  This needs changes that include changing pom file to include accumulo jars, better error handling during ingest, better error handling in the REST endpoint service and the addition of web server config files.

**Comment by datasedai** [comment]
So what I understand your tasks to be:
- Add a profile or something to more easily build the stanag war with the required dependencies, including Accumulo, etc
- Add template web server config files

Can you describe what type of error handling would be useful for you during ingest and in the REST endpoint service?  Is this just additional logging?
