### ISSUE TITLE
Permit selection of temporal binning strategy unit of measure

### ISSUE THREAD

**Issue by rwgdrummer** [ngageoint/geowave#782]
TemporalBinningStrategy assumes milliseconds.
Many of the temporal data processed by GeoWave is second granularity.
Configuring the strategy with second instead of millisecond reduces the scale of each hypercube.

TimeDefinition takes a unit defines unit for bin size.
TimeDefinition should a unit defines unit for bin size AND time unit size.

Note: Time/Date is still presented as a java.util.Date, which is millisecond granularity.
Is their a general solution to choose the granularity?

**Comment by rwgdrummer** [comment]
See #555

**Comment by residentx10** [comment]
I'll push on your PowerBI issues today. Since I'm in the same timezone as
Microsoft. Did you post in the forums?

**Comment by residentx10** [comment]
wrong reply :-)

**Comment by rwgdrummer** [comment]
After some investigation, we have decided this would not yield better results
