### ISSUE TITLE
DataIdQuery limit set at 1

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#809]
A list of Data IDs can be given for the query but for some reason the limit is being intentionally set to 1.

This was initially pointed out on the mailing list:
https://locationtech.org/mhonarc/lists/geowave-dev/msg00175.html

**Comment by rwgdrummer** [comment]
I noticed that as well.   This is specific to the AccumuloDataStore.
Difficult to recall the history.  It is clearly not needed in this case.
