### ISSUE TITLE
Error while installing on Ubuntu 1404: Requires: /bin/sh

### ISSUE THREAD

**Issue by dementiev** [ngageoint/geowave#817]
I'm trying to install geowave from RPM on Ubuntu 1404.
Accumulo/hadoop/zookeeper are successfully installed (I followed this instructions: http://blog.viggy.in/?p=841 )

#rpm -qa | grep geowave
geowave-repo-1.0-3.noarch
#uname -a
Linux Ubuntu-1404-trusty-64-minimal 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

yum --enablerepo=geowave install geowave-0.9.0-cdh5-accumulo -v
leads to following:
Failed to set locale, defaulting to C
Config time: 0.008
repo time: 0.000
Yum Version: 3.4.3
Setting up Package Sacks
pkgsack time: 0.005
rpmdb time: 0.002
Setting up Install Process
Obs Init time: 0.000
Resolving Dependencies
--> Running transaction check
---> Package geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 will be installed
Checking deps for geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('geowave-0.9.0-cdh5-tools', 'EQ', ('0', '0.9.0', None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('core', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch requires: geowave-0.9.0-cdh5-tools = 0.9.0
--> Processing Dependency: geowave-0.9.0-cdh5-tools = 0.9.0 for package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
Searching pkgSack for dep: geowave-0.9.0-cdh5-tools
Building updates object
up:simple updates time: 0.000
up:obs time: 0.000
up:condense time: 0.000
updates time: 0.001
TSINFO: Marking geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch as install for geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch requires: core
--> Processing Dependency: core for package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
Searching pkgSack for dep: core
TSINFO: Marking geowave-core-0.9.1-201605202017.noarch as install for geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
--> Running transaction check
---> Package geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 will be installed
Checking deps for geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('geowave-0.9.0-cdh5-tools', 'EQ', ('0', '0.9.0', None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('core', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-accumulo.noarch 0:0.9.0-201602011957 - u
geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
---> Package geowave-0.9.0-cdh5-tools.noarch 0:0.9.0-201602011957 will be installed
Checking deps for geowave-0.9.0-cdh5-tools.noarch 0:0.9.0-201602011957 - u
looking for ('core', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-tools.noarch 0:0.9.0-201602011957 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-tools.noarch 0:0.9.0-201602011957 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-0.9.0-cdh5-tools.noarch 0:0.9.0-201602011957 - u
geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
---> Package geowave-core.noarch 0:0.9.1-201605202017 will be installed
Checking deps for geowave-core.noarch 0:0.9.1-201605202017 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-core.noarch 0:0.9.1-201605202017 - u
looking for ('/bin/sh', None, (None, None, None)) as a requirement of geowave-core.noarch 0:0.9.1-201605202017 - u
geowave-core-0.9.1-201605202017.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-core-0.9.1-201605202017.noarch
Searching pkgSack for dep: /bin/sh
geowave-core-0.9.1-201605202017.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-core-0.9.1-201605202017.noarch
Searching pkgSack for dep: /bin/sh
geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
geowave-core-0.9.1-201605202017.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-core-0.9.1-201605202017.noarch
Searching pkgSack for dep: /bin/sh
geowave-core-0.9.1-201605202017.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-core-0.9.1-201605202017.noarch
Searching pkgSack for dep: /bin/sh
geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch requires: /bin/sh
--> Processing Dependency: /bin/sh for package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch
Searching pkgSack for dep: /bin/sh
--> Finished Dependency Resolution
Dependency Process ending
Depsolve time: 0.022
Error: Package: geowave-0.9.0-cdh5-accumulo-0.9.0-201602011957.noarch (geowave)
           Requires: /bin/sh
Error: Package: geowave-core-0.9.1-201605202017.noarch (geowave)
           Requires: /bin/sh
Error: Package: geowave-0.9.0-cdh5-tools-0.9.0-201602011957.noarch (geowave)
           Requires: /bin/sh
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Thank you for the help.

**Comment by rfecher** [comment]
Debian installers (#236) is currently an outstanding issue.  Installing using RPM should be better for RHEL, CentOS, Amazon Linux, etc. but installing from managed packages on Ubuntu would likely depend on #236.

**Comment by rfecher** [comment]
Issue is now captured in #236, to provide Debian packaging for install on Ubuntu, under current milestone.
