### ISSUE TITLE
Investigate the use of multiple scanners with single ranges vs. one scanner with multiple ranges

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#859]
We want to optimize for performance and understand the impact of best usage of the scanner.

**Comment by blastarr** [comment]
Start here: https://github.com/ngageoint/geowave/blob/master/extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/query/HBaseFilteredIndexQuery.java#L123

**Comment by blastarr** [comment]
In HBaseFilteredIndexQuery, I added a static boolean called MULTI_FILTER to control whether the query uses a single scanner + MultiRowRangeFilter w/ a list of ranges (true), or a list of single-range scanners (false)

**Comment by blastarr** [comment]
Initial analysis of queries run during GeoWaveBasicIT shows that on average, a single scanner w/ a multi-filter runs about 3x faster than a list of single-range scanners (running on single-node VM env).  
  
Next step would be to run tests for comparison on a cluster.

**Comment by blastarr** [comment]
Spreadsheet comparing new multi-filter scan vs old list of single-range scans. On average the old query took 2.4 times longer to run than the new.

[queryperf.xlsx](https://github.com/ngageoint/geowave/files/362412/queryperf.xlsx)

**Comment by blastarr** [comment]
Run on AWS EMR 3-node cluster, showed multi-filter outperforming single ranges by a bit more. Avereage perf diff increased from 2.4x to 3.3x  
  
[queryperfaws.xlsx](https://github.com/ngageoint/geowave/files/362769/queryperfaws.xlsx)

**Comment by blastarr** [comment]
Ran a comparision of HBase mods against baseline Accumulo for reference. Current HBase query performance is running 2x to 5x faster than Accumulo in the GeoWaveBasicIT.
[querycomp.xlsx](https://github.com/ngageoint/geowave/files/384980/querycomp.xlsx)

**Comment by blastarr** [comment]
This ticket has become a catch-all for HBase performance experiments. Currently, the HBase impl has improved significantly in both query & ingest perf over the original impl, but is still slower than Accumulo.

**Comment by blastarr** [comment]
After profiling HBase ingest, it appears that about 80% of the time taken to ingest GDELT data is consistently attributable to the actual atomic mutator.mutate call.  
  
Attached spreadsheet shows times (in seconds) per day of GDELT ingest. The "DB Write" value is that single mutate call:  
  
[IngestProfile.xlsx](https://github.com/ngageoint/geowave/files/418729/IngestProfile.xlsx)

**Comment by blastarr** [comment]
After applying Rich's fix for the Write Buffer bug, we are now seeing a reasonable ingest performance from HBase. Attached is the spreadsheet comparing HBase vs Accumulo for a month of GDELT, showing that HBase is about 5% slower than Accumulo.
[ingest-compare-H-vs-A.xlsx](https://github.com/ngageoint/geowave/files/423215/ingest-compare-H-vs-A.xlsx)

**Comment by blastarr** [comment]
Based on testing, we are close to Accumulo performance on ingest and query with HBase. Cleanup/format/test today.
