### ISSUE TITLE
Improve unit test coverage for GeoWave formats

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#995]
With the exception of gdelt, most of the geowave format projects have no unit test coverage. The raster and vector formats are well covered through integration tests, but the other formats (avero, geolife, gpx, etc.) need unit test coverage to be added.

**Comment by Becca42** [comment]
Is there additional documentation on these formats available? It would be helpful to know what is expected in each format. E.g. in the GDELT tests only some attributes seem to be required for the feature to be valid.

**Comment by mawhitby** [comment]
We don't have any specific documentation on the required features of each of the format types, but you should be able to find that information in the IngestPlugin classes of the various formats.

**Comment by Becca42** [comment]
Are there any resources to test on like '20130401.export.CSV.zip' in GDELT test resources for the other formats?

**Comment by mawhitby** [comment]
That is something you'll need to add for your unit tests. Most of the formats can be found online and freely downloaded. 

The one major caveat to that is, make sure you use a relatively small subset of data. Every person who downloads geowave will also be downloading whatever files you add for the test so we don't want anything too large in there.

**Comment by mawhitby** [comment]
Tests add in PR #1025
