### ISSUE TITLE
Add Unit tests to the package mil.nga.giat.geowave.cli.geoserver

### ISSUE THREAD

**Issue by rfecher** [ngageoint/geowave#998]
There are currently no unit tests of any of the public methods in the java classes inside the mil.nga.giat.geowave.cli.geoserver package.  These are commands exposed to the GeoWave command line tool that interact with REST services on GeoServer to more easily integrate GeoWave with GeoServer for users.

**Comment by mrkev** [comment]
Hello! A couple of questions, if you don't mind me asking? 
 1. Was just wondering what my strategy should be fore this.

**Comment by mrkev** [comment]
Hello! A couple of questions, if you don't mind me asking!

1. Im wondering what my strategy should be for testing this. My guess is that I want to test it against a running instance GeoServer; should I start it or assume it's running already? Is there mock data anywhere I can use, or should I find some myself? 
2. I guess going off of 1, I see most classes are *Command classes which seem to just call operations on GeoServerRestClient. How should I test these / should I test these? It might be redundant if we're testing GeoServerRestClient throughly

**Comment by mawhitby** [comment]
I would advise against spinning up a GeoServer instance in the unit tests and yes we don't really want to test GeoSever's functionality. We can talk more about it during our weekly meeting.

**Comment by rfecher** [comment]
pulled in via https://github.com/ngageoint/geowave/commit/8dd9cf9caaad36c1c36d778a0e2158a47bf6d7dc
